all:
	$(MAKE) -C src
	mv src/CLIENT_blinding_message .
	mv src/SIGNER_MSS_keygen .
	mv src/SIGNER_MSS_sign .
	mv src/CLIENT_blind_sign .
	mv src/VERIFIER_verify .

clean:
	rm -f CLIENT_blinding_message SIGNER_MSS_keygen SIGNER_MSS_sign CLIENT_blind_sign VERIFIER_verify MSS*.txt *.bin

help:
	@echo "\nUsage:\n"
	@echo "make [all]:	Build 4 binaries: commitment_gen, sign, prover, verifier."
	@echo "		Please read README.md or use '-h/--help' option on each binary for more information.\n"
	@echo "make clean:	Remove all files generated by make.\n"
	@echo "make help:	Display this help.\n"
